services:
  # Web Service
  - type: web
    name: voteapp
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput --clear
    startCommand: python manage.py migrate && gunicorn voteapp.wsgi:application --workers 4 --threads 4 --worker-class gthread --worker-connections 1000 --timeout 60 --bind 0.0.0.0:$PORT
    healthCheckPath: /accounts/login/
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: voting-app-wvk6.onrender.com,localhost,127.0.0.1
      # Cloudinary Configuration for Media Files
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      # Arkesel SMS Gateway Configuration
      - key: ARKESEL_API_KEY
        sync: false
      - key: ARKESEL_SENDER_ID
        value: VoteApp
