# Generated by Django 4.2.30 on 2026-09-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_unique_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('voter', 'Voter'), ('admin', 'System Administrator'), ('officer', 'Electoral Commissioner'), ('registrar', 'Voter Registrar'), ('auditor', 'Election Auditor')], default='voter', max_length=20),
        ),
    ]
